# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-14 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='username',
        ),
    ]
