# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-14 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200214_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
