# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-14 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200214_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='test',
            name='password',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='username',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
