# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200214_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['c_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='test',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32),
        ),
        migrations.AlterField(
            model_name='test',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='username',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
