# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-14 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200214_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='username',
            new_name='name',
        ),
    ]
