# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200325_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selfinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=0, max_length=50, unique=True)),
                ('real_name', models.CharField(blank=True, default=0, max_length=50, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('phone_number', models.CharField(blank=True, default=0, max_length=11)),
                ('email', models.EmailField(blank=True, default=0, max_length=254, unique=True)),
                ('education', models.CharField(blank=True, choices=[('technical secondary school and above', '中专及以下'), ('jonior college', '大专'), ('undergratuate', '本科'), ('master', '硕士'), ('doctor and above', '博士及以上')], default='中专及以下', max_length=50)),
                ('major', models.CharField(blank=True, default=0, max_length=50)),
                ('age', models.CharField(blank=True, choices=[('below 20', '20以下'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('above 50', '50以上')], default='20以下', max_length=50)),
                ('expected_salary', models.CharField(blank=True, choices=[('below 3000', '3000以下'), ('3000-5000', '3000-5000'), ('5000-8000', '5000-8000'), ('8000-10000', '8000-10000'), ('above 10000', '10000以上')], default='3000以下', max_length=50)),
                ('home_address', models.CharField(blank=True, default=0, max_length=150, unique=True)),
                ('certificate_or_skills', models.CharField(blank=True, default=0, max_length=150, unique=True)),
                ('professional_history', models.CharField(blank=True, default=0, max_length=150, unique=True)),
                ('experience', models.CharField(blank=True, default=0, max_length=150, unique=True)),
                ('hobby', models.CharField(blank=True, default=0, max_length=150, unique=True)),
                ('selfintroduction', models.CharField(blank=True, default=0, max_length=150, unique=True)),
            ],
        ),
    ]
