# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-17 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200416_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=0, max_length=50, unique=True)),
                ('plan1', models.CharField(blank=True, default=0, max_length=256)),
                ('plan2', models.CharField(blank=True, default=0, max_length=256)),
                ('plan3', models.CharField(blank=True, default=0, max_length=256)),
            ],
        ),
    ]
