# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan1',
            field=models.CharField(blank=True, default='专家尚未制定，请耐心等待', max_length=256),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan2',
            field=models.CharField(blank=True, default='专家尚未制定，请耐心等待', max_length=256),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan3',
            field=models.CharField(blank=True, default='专家尚未制定，请耐心等待', max_length=256),
        ),
    ]
