# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-18 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200417_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plandone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=0, max_length=50, unique=True)),
                ('progress', models.CharField(blank=True, choices=[('0', '未开始'), ('25%', '完成了1/4'), ('50%', '完成了一半'), ('75%', '完成了3/4'), ('100%', '全部完成')], default='未开始', max_length=50)),
                ('learning_log', models.CharField(blank=True, default='专家尚未制定，请耐心等待', max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='certificate_or_skills',
            field=models.CharField(blank=True, default='未填写', max_length=150),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='experience',
            field=models.CharField(blank=True, default='未填写', max_length=150),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='hobby',
            field=models.CharField(blank=True, default='未填写', max_length=150),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='home_address',
            field=models.CharField(blank=True, default='未填写', max_length=150),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='major',
            field=models.CharField(blank=True, default='未填写', max_length=50),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='phone_number',
            field=models.CharField(blank=True, default='未填写', max_length=11),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='professional_history',
            field=models.CharField(blank=True, default='未填写', max_length=150),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='real_name',
            field=models.CharField(blank=True, default='未填写', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='selfintroduction',
            field=models.CharField(blank=True, default='未填写', max_length=150),
        ),
    ]
