# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-18 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200418_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plandone',
            old_name='progress',
            new_name='plan1_progress',
        ),
        migrations.RemoveField(
            model_name='plandone',
            name='learning_log',
        ),
        migrations.AddField(
            model_name='plandone',
            name='plan1_learning_log',
            field=models.CharField(blank=True, default='暂无记录', max_length=1024),
        ),
        migrations.AddField(
            model_name='plandone',
            name='plan2_learning_log',
            field=models.CharField(blank=True, default='暂无记录', max_length=1024),
        ),
        migrations.AddField(
            model_name='plandone',
            name='plan2_progress',
            field=models.CharField(blank=True, choices=[('0', '未开始'), ('25%', '完成了1/4'), ('50%', '完成了一半'), ('75%', '完成了3/4'), ('100%', '全部完成')], default='未开始', max_length=50),
        ),
        migrations.AddField(
            model_name='plandone',
            name='plan3_learning_log',
            field=models.CharField(blank=True, default='暂无记录', max_length=1024),
        ),
        migrations.AddField(
            model_name='plandone',
            name='plan3_progress',
            field=models.CharField(blank=True, choices=[('0', '未开始'), ('25%', '完成了1/4'), ('50%', '完成了一半'), ('75%', '完成了3/4'), ('100%', '全部完成')], default='未开始', max_length=50),
        ),
    ]
