# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20200418_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfinfo',
            name='real_name',
            field=models.CharField(blank=True, default='未填写', max_length=50),
        ),
    ]
