# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20200418_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sex',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='男', max_length=32),
        ),
    ]
