# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-18 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20200418_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfinfo',
            name='name',
            field=models.CharField(blank=True, default=0, max_length=50, unique=True),
        ),
    ]
