# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-20 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200418_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, default=0, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default=0, max_length=512)),
                ('requirement', models.CharField(blank=True, default=0, max_length=512)),
                ('salary', models.CharField(blank=True, choices=[('3000以下', '3000以下'), ('3000-5000', '3000-5000'), ('5000-8000', '5000-8000'), ('8000-10000', '8000-10000'), ('10000以上', '10000以上')], default='3000以下', max_length=32)),
                ('character', models.CharField(blank=True, default=0, max_length=256)),
            ],
        ),
    ]
