# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='无标题', max_length=128)),
                ('content', models.CharField(blank=True, default='未编辑', max_length=4096)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '职业资讯',
                'verbose_name_plural': '职业资讯',
                'ordering': ['c_time'],
            },
        ),
    ]
