# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_jobnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Euser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(blank=True, default=0, max_length=50, unique=True)),
                ('password', models.CharField(blank=True, default=0, max_length=50)),
                ('email', models.EmailField(blank=True, default=0, max_length=254)),
                ('sex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('aspect', models.CharField(blank=True, default=0, max_length=128)),
                ('usernumber', models.SmallIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': '专家',
                'verbose_name_plural': '专家',
                'ordering': ['c_time'],
            },
        ),
    ]
