# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-23 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_euser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euser',
            name='email',
        ),
    ]
