# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20200423_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='euser',
            name='aspect',
            field=models.CharField(blank=True, default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='euser',
            name='email',
            field=models.EmailField(blank=True, default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='euser',
            name='sex',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='男', max_length=32),
        ),
        migrations.AddField(
            model_name='euser',
            name='usernumber',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
