# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20200423_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfinfo',
            name='expert',
            field=models.CharField(blank=True, default='未分配', max_length=128),
        ),
        migrations.AlterField(
            model_name='euser',
            name='aspect',
            field=models.CharField(blank=True, default='未填写', max_length=128),
        ),
    ]
