# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20200423_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='expert',
            field=models.CharField(blank=True, default='未分配', max_length=128),
        ),
        migrations.AddField(
            model_name='plandone',
            name='expert',
            field=models.CharField(blank=True, default='未分配', max_length=128),
        ),
    ]
