# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-15 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20200423_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfinfo',
            name='hobby',
            field=models.CharField(blank=True, choices=[('常规型', '常规型'), ('艺术型', '艺术型'), ('实践型', '实践型'), ('社会型', '社会型'), ('研究型', '研究型'), ('管理型', '管理型')], default='未填写', max_length=150),
        ),
    ]
