# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-15 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20200515_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfinfo',
            name='personality',
            field=models.CharField(blank=True, choices=[('ISTJ稽查员', 'ISTJ稽查员'), ('ISFJ保护者', 'ISFJ保护者'), ('ISTP操作者/演奏者', 'ISTP操作者/演奏者'), ('ISFP作曲家/艺术家', 'ISFP作曲家/艺术家'), ('INFJ咨询师', 'INFJ咨询师'), ('INFP治疗师/导师', 'INFP治疗师/导师'), ('INTJ智多星/科学家', 'INTJ智多星/科学家'), ('INTP建筑师/设计师', 'INTP建筑师/设计师'), ('ESTJ督导', 'ESTJ督导'), ('ESFJ供给者/销售员', 'ESFJ供给者/销售员'), ('ESTP发起者/创设者', 'ESTP发起者/创设者'), ('ESFP表演者/示范者', 'ESFP表演者/示范者'), ('ENFJ教师', 'ENFJ教师'), ('ENFP倡导者/激发者', 'ENFP倡导者/激发者'), ('ENTJ统帅/调度', 'ENTJ统帅/调度'), ('ENTP发明家', 'ENTP发明家')], default='未填写', max_length=150),
        ),
    ]
