# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-15 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_selfinfo_personality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='character',
        ),
        migrations.AddField(
            model_name='job',
            name='degree',
            field=models.CharField(blank=True, choices=[('中专及以下', '中专及以下'), ('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('博士及以上', '博士及以上')], default='中专及以下', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, default=0, max_length=1024),
        ),
        migrations.AddField(
            model_name='job',
            name='hobby1',
            field=models.CharField(blank=True, choices=[('常规型', '常规型'), ('艺术型', '艺术型'), ('实践型', '实践型'), ('社会型', '社会型'), ('研究型', '研究型'), ('管理型', '管理型')], default='常规型', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='hobby2',
            field=models.CharField(blank=True, choices=[('常规型', '常规型'), ('艺术型', '艺术型'), ('实践型', '实践型'), ('社会型', '社会型'), ('研究型', '研究型'), ('管理型', '管理型')], default='常规型', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='hobby3',
            field=models.CharField(blank=True, choices=[('常规型', '常规型'), ('艺术型', '艺术型'), ('实践型', '实践型'), ('社会型', '社会型'), ('研究型', '研究型'), ('管理型', '管理型')], default='常规型', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='job_score',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='major1',
            field=models.CharField(blank=True, default='无限制', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='major2',
            field=models.CharField(blank=True, default='无限制', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='major3',
            field=models.CharField(blank=True, default='无限制', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='personality1',
            field=models.CharField(blank=True, choices=[('ISTJ稽查员', 'ISTJ稽查员'), ('ISFJ保护者', 'ISFJ保护者'), ('ISTP操作者/演奏者', 'ISTP操作者/演奏者'), ('ISFP作曲家/艺术家', 'ISFP作曲家/艺术家'), ('INFJ咨询师', 'INFJ咨询师'), ('INFP治疗师/导师', 'INFP治疗师/导师'), ('INTJ智多星/科学家', 'INTJ智多星/科学家'), ('INTP建筑师/设计师', 'INTP建筑师/设计师'), ('ESTJ督导', 'ESTJ督导'), ('ESFJ供给者/销售员', 'ESFJ供给者/销售员'), ('ESTP发起者/创设者', 'ESTP发起者/创设者'), ('ESFP表演者/示范者', 'ESFP表演者/示范者'), ('ENFJ教师', 'ENFJ教师'), ('ENFP倡导者/激发者', 'ENFP倡导者/激发者'), ('ENTJ统帅/调度', 'ENTJ统帅/调度'), ('ENTP发明家', 'ENTP发明家')], default='ISTJ稽查员', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='personality2',
            field=models.CharField(blank=True, choices=[('ISTJ稽查员', 'ISTJ稽查员'), ('ISFJ保护者', 'ISFJ保护者'), ('ISTP操作者/演奏者', 'ISTP操作者/演奏者'), ('ISFP作曲家/艺术家', 'ISFP作曲家/艺术家'), ('INFJ咨询师', 'INFJ咨询师'), ('INFP治疗师/导师', 'INFP治疗师/导师'), ('INTJ智多星/科学家', 'INTJ智多星/科学家'), ('INTP建筑师/设计师', 'INTP建筑师/设计师'), ('ESTJ督导', 'ESTJ督导'), ('ESFJ供给者/销售员', 'ESFJ供给者/销售员'), ('ESTP发起者/创设者', 'ESTP发起者/创设者'), ('ESFP表演者/示范者', 'ESFP表演者/示范者'), ('ENFJ教师', 'ENFJ教师'), ('ENFP倡导者/激发者', 'ENFP倡导者/激发者'), ('ENTJ统帅/调度', 'ENTJ统帅/调度'), ('ENTP发明家', 'ENTP发明家')], default='ISTJ稽查员', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='personality3',
            field=models.CharField(blank=True, choices=[('ISTJ稽查员', 'ISTJ稽查员'), ('ISFJ保护者', 'ISFJ保护者'), ('ISTP操作者/演奏者', 'ISTP操作者/演奏者'), ('ISFP作曲家/艺术家', 'ISFP作曲家/艺术家'), ('INFJ咨询师', 'INFJ咨询师'), ('INFP治疗师/导师', 'INFP治疗师/导师'), ('INTJ智多星/科学家', 'INTJ智多星/科学家'), ('INTP建筑师/设计师', 'INTP建筑师/设计师'), ('ESTJ督导', 'ESTJ督导'), ('ESFJ供给者/销售员', 'ESFJ供给者/销售员'), ('ESTP发起者/创设者', 'ESTP发起者/创设者'), ('ESFP表演者/示范者', 'ESFP表演者/示范者'), ('ENFJ教师', 'ENFJ教师'), ('ENFP倡导者/激发者', 'ENFP倡导者/激发者'), ('ENTJ统帅/调度', 'ENTJ统帅/调度'), ('ENTP发明家', 'ENTP发明家')], default='ISTJ稽查员', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.CharField(blank=True, default='无要求', max_length=256),
        ),
    ]
