# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-15 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20200515_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hobby1',
            field=models.CharField(blank=True, choices=[('常规型', '常规型'), ('艺术型', '艺术型'), ('企业型', '企业型'), ('社会型', '社会型'), ('研究型', '研究型'), ('管理型', '管理型')], default='常规型', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='hobby2',
            field=models.CharField(blank=True, choices=[('常规型', '常规型'), ('艺术型', '艺术型'), ('企业型', '企业型'), ('社会型', '社会型'), ('研究型', '研究型'), ('管理型', '管理型')], default='常规型', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='hobby3',
            field=models.CharField(blank=True, choices=[('常规型', '常规型'), ('艺术型', '艺术型'), ('企业型', '企业型'), ('社会型', '社会型'), ('研究型', '研究型'), ('管理型', '管理型')], default='常规型', max_length=32),
        ),
    ]
